services:
  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    command: http vk-bot:8080
    environment:
      - NGROK_AUTHTOKEN=
  vk-bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - VK_ACCESS_TOKEN=
      - VK_SECRET=
      - VK_CONFIRMATION_CODE=
    depends_on:
      - ngrok
    volumes:
      - ./logs:/app/logs

volumes:
  logs_volume: